packages/example/src/Application.ts, packages/example/src/indexers/BalanceIndexer.ts, packages/example/src/indexers/FakeClockIndexer.ts, packages/example/src/indexers/TvlIndexer.ts, packages/example/src/repositories/TvlRepository.ts
This allows adding more complexity to the example pipeline and validates the idea of self-invalidation inside the indexer (BalanceIndexer can now decide it wants to invalidate).
=> Add TVL indexer to the example package

packages/backend-tools/src/logger/formatTimePretty.ts
This PR aims to add indicator to timestamp if time is given in UTC
```tsx
utc: true
...
BEFORE:
16:07:26.820
AFTER:
16:07:26.820 (UTC)
```
=> Add UTC indicator if it is turned on

.changeset/dry-maps-exercise.md, packages/example/src/Application.ts, packages/example/src/Config.ts, packages/example/src/indexers/ABC_Indexer.ts, packages/example/src/indexers/AB_BC_Indexer.ts, packages/example/src/repositories/ABC_Repository.ts, packages/example/src/repositories/AB_BC_Repository.ts, packages/uif/src/BaseIndexer.test.ts, packages/uif/src/BaseIndexer.ts, packages/uif/src/SliceIndexer.test.ts, packages/uif/src/SliceIndexer.ts, packages/uif/src/index.ts
Resolves L2B-1928
This PR adds an additional class `SliceIndexer`, enabling an Indexer to index several independent states, e.g. Balances of tokens. Those independent states are called `Slices`. We store the height of each of the slices along with `mainHeight`, which is the minimum of parents' heights AND the `safeHeight` of the indexer. The `getSafeHeight` of the `SliceIndexer` returns a minimum of each of the slices' height and the `mainHeight`.
Implementation of the `SliceIndexer` in the user app requires defining the following methods: 
- `abstract getMainSafeHeight(): Promise<number>`
- `abstract setMainSafeHeight(height: number): Promise<void>`
- `abstract getExpectedSlices(): SliceHash[]`
- `abstract getSliceStates(): Promise<SliceState[]>`
- `abstract removeSlices(hashes: …
=> Enable slice invalidation

.changeset/popular-fans-return.md, packages/discovery/package.json, packages/discovery/src/discovery/output/diffDiscovery.test.ts, packages/discovery/src/discovery/output/diffDiscovery.ts, packages/discovery/src/discovery/runDiscovery.ts
- Synced backend changes with discovery package due to upcoming migration
https://github.com/l2beat/l2beat/pull/1861
https://github.com/l2beat/l2beat/pull/1885
Please give me a heads-up in case I missed anything
=> Pick: sync latest backend changes to discovery layer

.changeset/cyan-gifts-smoke.md, packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/source/SourceCodeService.ts, packages/discovery/src/discovery/source/getDerivedName.ts
During a migration to a standalone `discovery` package, a bug was introduced. It resulted in an assertion error being thrown when discovering a contract that is not verified on etherscan. Despite our [Discovery Grafana dashboard](https://l2beat.grafana.net/d/PPJiIqA4k/discovery?orgId=1) knowing about this issue and the amount of errors being thrown during discovery, we did not get any notification about this problem.
Merging this PR will result in `@l2beat/discovery@0.2.1` being published
=> Fix assertion error when contract code is not verified

.changeset/smart-colts-carry.md, packages/discovery/src/discovery/handlers/storageCommon.ts, packages/discovery/src/discovery/handlers/user/DynamicArrayHandler.test.ts, packages/discovery/src/discovery/handlers/user/DynamicArrayHandler.ts, packages/discovery/src/discovery/handlers/user/StorageHandler.ts, packages/discovery/src/discovery/handlers/user/index.ts
Resolves L2B-2408
DynamicArrayHandler allows you to fetch internal dynamic arrays from the storage of a contract. It expects that the user provides the starting slot (where the length of the dynamic array is located, it's easy to get this number using a website like [evm.storage](https://evm.storage/)) and the type of the element that is stored. Currently only addresses are supported.
=> Add DynamicArrayHandler

.changeset/wild-avocados-push.md, packages/discovery/src/config/config.discovery.ts, packages/discovery/src/discovery/DiscoveryLogger.ts, packages/discovery/src/discovery/analysis/AddressAnalyzer.test.ts, packages/discovery/src/discovery/analysis/AddressAnalyzer.ts, packages/discovery/src/discovery/output/toDiscoveryOutput.test.ts, packages/discovery/src/discovery/provider/DiscoveryProvider.test.ts, packages/discovery/src/discovery/provider/DiscoveryProvider.ts, packages/discovery/src/discovery/provider/ProviderWithCache.ts, packages/discovery/src/discovery/runDiscovery.ts, packages/discovery/src/singleDiscovery.ts
Resolves L2B-2573
Calling `getLogs()` to Ethereum RPC is slow and resource intensive. That's why most RPC providers limit the range than can be queried in one call (e.g. QuickNode limits to 10,000 block range). 
Up until now we were fine querying Alchemy for range [0-now], because it allows it (it probably uses some custom, efficient index, instead of going through bloom filers of each block, like normal nodes do). But to switch to QuickNode we need to start querying in batches.
Since querying in batches is much slower than full range at Alchemy (~1s for full range in Alchemy vs. 5 minutes for the same range in steps from QuickNode or even local node), we need to rely on caching. With cache, after first run, only the most recent range needs to be queried, which is as fast or even faster …
=> Fetch logs in batches, with cache-friendly ranges

.github/workflows/release.yml
Current version fails with this error:
🦋  error an error occurred while publishing @l2beat/discovery: ENEEDAUTH This command requires you to be logged in to https://registry.npmjs.org/ 
According to documentation at https://github.com/changesets/action there needs to be a .npmrc created (if we're not explicitly using `changsets/action@v1` which creates this file)
=> Update release action to create .npmrc

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/DiscoveryLogger.ts, packages/discovery/src/discovery/analysis/AddressAnalyzer.ts, packages/discovery/src/discovery/output/toDiscoveryOutput.ts
Resolves L2B-2722
Celoscan even though it's an Etherscan product does not support the `contract/getcontractcreation` endpoint even though their API docs say it's supported. This PR allows the call to this endpoint to fail and if that happens it will just ignore the `sinceTimestamp` without writing anything into the `discovered.json`.
=> Allow the contract deployment query to fail

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/config/config.discovery.ts, packages/discovery/src/discovery/analysis/AddressAnalyzer.test.ts, packages/discovery/src/discovery/analysis/AddressAnalyzer.ts, packages/discovery/src/discovery/handlers/user/ConstructorArgsHandler.ts, packages/discovery/src/discovery/provider/DiscoveryProvider.ts, packages/discovery/src/discovery/provider/ProviderWithCache.ts, packages/discovery/src/discovery/proxies/auto/StarkWareProxyGovernance.ts, packages/discovery/src/utils/EtherscanClient.ts, packages/discovery/src/utils/EtherscanLikeClient.ts
Resolves L2B-2747
The previous solution was to treat an error from Etherscan as inability to perform a given method. But sometimes Etherscan like endpoints just fail and not because they do not support a called method. This in turn caused chaos on our Update Monitor where every hour at least one call failed and the diffs where flooding the discord channel because it didn't refetch the information like it should.
Now you have the ability to specify that a given Etherscan like endpoint does not support some method. This will return undefined and the caller has to handle the possibility of that happening.
=> Allow the configured etherscan clients to fail

.changeset/happy-brooms-prove.md, packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/provider/ProviderWithCache.ts, packages/discovery/src/discovery/provider/SQLiteCache.test.ts, packages/discovery/src/discovery/provider/SQLiteCache.ts
Quick and dirty in-time cache reference discriminated by block number where possible. If cache has no in-time identity, then  null is being inserted.
=> Add cache point-in-time identity

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/user/LayerZeroMultisigHandler.ts
Fixes the following console bug:
=> Fix unknown modifier ethers bug

packages/example/src/Application.ts, packages/example/src/indexers/BlockNumberIndexer.ts, packages/uif/CHANGELOG.md, packages/uif/package.json, packages/uif/src/BaseIndexer.ts
Resolves L2B-2820
Because `DEFAULT_RETRY_STRATEGY` was a static field on `BaseIndexer`, the functions were shared between all the Indexers. In particular the `clear` function was shared, which caused the memoizes `attempts` value to reset for **ALL THE INDEXERS IN THE SYSTEM**. This PR changes the static field to a static method which fixes this issue.
=> Fix default retry strategy unexpected attempts reset

packages/discovery/.gitignore
If you run discovery in the tools package the cache shows up in the `git status`. To make it go away I've added the cache path to the .gitignore file.
=> Add discovery cache to .gitignore

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/provider/ProviderWithCache.test.ts, packages/discovery/src/discovery/provider/ProviderWithCache.ts
Resolves L2B-2733
Reorg protection is optional. If `safeReorgDepth` is not passed to `ProviderWithCache`, it behaves like always and caches everything. Reorg protection needs to be implemented by the caller.
If `safeReorgDepth` is provided, `ProviderWithCache` will not cache anything (that provides relevant blockNumber) when it's too close to current block number (which is refreshed every minute).
=> Add reorg protection to ProviderWithCache, based on safe depth

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/provider/ProviderWithCache.test.ts, packages/discovery/src/discovery/provider/ProviderWithCache.ts, packages/discovery/src/discovery/provider/SQLiteCache.test.ts
Resolves L2B-2888
Up til now, `blockNumber` was optional when working with cache entries since `getTranasction` was unable to provide viable block number to reference to when invalidating cache.
**Important**: Explicit error will be thrown mid-way since we don't want to cache nor return transactions that have not yet been mined.
**Important V2**: Any existing cache must be **pruned** off `getTransaction` cache entries since those will have no time reference and cannot be invalidated, thus poisoning the cache.
=> Require block number when working with cache (getTransaction)

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/getHandlers.test.ts, packages/discovery/src/discovery/handlers/getSystemHandlers.ts
If a abi function doesn't return anything, we should not call it. Currently it's shown as returning empty array, which is not right.
=> Dont discover fnunctions with no output

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/provider/ProviderWithCache.ts
Contract code can change at any moment, so we cache *with blockNumber*
see: https://medium.com/coinmonks/dark-side-of-create2-opcode-6b6838a42d71
Another problem is running discovery on a very old block number
when some contract has not been deployed yet:
getCode() would return previously cached value instead of empty code.
=> Cache getCode() with blockNumber

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/reference.ts
Only undefined values should throw a dependency error.
=> Fix dependency error when value is 0

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/index.ts, packages/discovery/src/utils/EtherscanLikeClient.ts
Some platforms such as Routescan are almost fully-compatible with Etherscan-like API shape.
This modification enables us to extend Etherscanlike Client without rewriting it from scratch and altering only certain things.
=> Change etherscan client props' privacy scope

package.json, packages/discovery-types/CHANGELOG.md, packages/discovery-types/package.json, packages/discovery-types/src/proxyDetails.ts, packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/proxies/auto/GnosisSafe.ts, packages/discovery/src/discovery/proxies/auto/GnosisSafeModule.ts, packages/discovery/src/discovery/utils/getSafeModules.ts
Resolves L2B-3207
The old implementation has some false positives, for example in Zora it mistook some Proxy for a Zodiac Module. This is because the old mnemonic was
1. check two special storage slots
2. if there are not zero it's a zodiac module
The slots in question are 102 and 103. They are quite big but can interfere with some other contracts - like in the case of Zora.
The new mnemonic is the following
1. check two special storage slots
2. call a getter function for the guard
3. if slots are non zero and the getter for the guard did not revert it's a zodiac module
The unfortunate surprise is the fact that not all Zodiac based modules have to have a recursive module list. For example the Linea [Roles contract](https://etherscan.deth.net/address/0xF24f1DC519d88246809B660eb56D94048575d0 …
=> Improve the Zodiac modules discovery implementation

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/user/OpDAHandler.ts
If the Celestia endpoint times out a given rollup will post to L1. This is non-deterministic and gives a lot of changes that are not important since it's possible that 1 transaction out of 10 will post to L1 and trigger a two changes: one change when it goes from `true->false` and the second when it goes to `false->true`.
=> opDAHandler now doesn't check every tx of the last 10

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/user/OpDAHandler.ts, packages/discovery/src/discovery/handlers/user/OpSequencerInboxHandler.ts, packages/discovery/src/discovery/provider/DiscoveryProvider.ts, packages/discovery/src/utils/EtherscanLikeClient.ts
The `txlist` method is also returning the incoming transactions, which is undesirable for us.
=> Filter out incoming transactions from etherscan response

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/engine/DiscoveryEngine.ts
Because we sanitize the discovery output by hiding the error messages before sending it to the update monitor, there was no way to see what caused some errors. This PR adds log that will be visible in server logs. Moreover, when creating a new discovery, the user will have more information about the errors, directly in the terminal.
=> Log errors during discovery

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/index.ts, packages/discovery/src/inversion/runInversion.ts
Two additional types need to be exported from discovery for l2beat templates.
I've renamed `AddressDetails` type to `InvertedAddressDetails` to make it more explicit where it is used.
=> Export InvertedAddressDetails and Role types

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/user/ArrayHandler.ts
Previously only uint256 and uint16 were support, probably by mistake.
=> Support all uint types in Array Handler

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/output/saveDiscoveryResult.ts
Fix an edge case in saving flattened source files
Suppose there are two contracts in a project. Both named "ContractA". If
we override the name of contract `#1` with "ContractB" its name is
going to be "ContractB" but its derived name is going to be equal to
"ContractA". SourceCodeService while generating sources does not reach
into overrides so the source name is always going to be the
"derivedName". We should always choose the derived name (if present, if
it's not, the name is equal to the derived name).
The edge case we've hit is that in the above example, while checking for
contract clashes we had an array that looked like `[ContractA,
ContractB]` instead of `[ContractA, ContractA]`.
=> Fix an edge case in saving flattened source files

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/cli/discoverCommand.ts, packages/discovery/src/cli/getCliParameters.test.ts, packages/discovery/src/cli/getCliParameters.ts, packages/discovery/src/config/config.discovery.ts, packages/discovery/src/config/types.ts, packages/discovery/src/discovery/output/saveDiscoveryResult.ts, packages/discovery/src/discovery/runDiscovery.ts
Resolves this suggestion by Peter
> So my understanding after reading this is that this option allows you to save output to a different folder than .code. I am not even sure how useful it is because it resolves relative to the discovered files and so it will still be in {projectName}/{chainName} right? Anyway, I don't feel like having sources outputted to foo and .flatfoo is what users would want. I feel like foo/.code and foo/.flat seem more desirable. Or provide two flags --code-folder and --flat-folder.
=> Add --flat-sources-folder cli flag

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/utils/normalizeDiffPath.test.ts, packages/discovery/src/discovery/utils/normalizeDiffPath.ts
Example update-monitor message that includes 2d-array
```diff
values.getProviderInfoAt.0.6:
-        -192
+        -833
```
```diff
values.getProviderInfoAt.0.5:
-        "535639074270563789506100"
+        "590078921054041246414598"
```
```diff
values.getProviderInfoAt.0.4:
-        "535639074270563789506292"
+        "590078921054041246415431"
```
```diff
values.getProviderInfoAt.0.2:
-        "535639074270563789506100"
+        "590078921054041246414598"
```
=> Allow for n-darray

packages/discovery/src/discovery/handlers/user/ArbitrumDACKeysetHandler.test.ts, packages/discovery/src/discovery/handlers/user/ArbitrumDACKeysetHandler.ts
This pull request updates the ArbitrumDACKeysetHandler class to use more descriptive variable names for clarity and readability. The variable names `threshold` and `keyCount` have been changed to `requiredSignatures` and `membersCount` respectively. Previously the names were incorrect as `threshold` was actually `assumedHonestMembers` and `threshold=keyCount-assumedHonestMembers+1`.
=> Update ArbitrumDACKeysetHandler to use more descriptive variable names

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/output/diffContracts.test.ts, packages/discovery/src/discovery/output/diffContracts.ts
Resolves L2B-4365
In all other places we use `.{index}` syntax to flatten array elements.
Having a single place where we do `[{index}]` messes up the meta.json
description generation. See the Discord message described in the linked
Linear issue to see an example.
=> Make the array syntax consistent

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/config/chains.ts, schemas/config.schema.json
It's sometimes useful to run discovery on the testnet. We need it in lz-monitoring to work on the v2 contracts.
=> Add testnets support to discovery

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/flatten/ParsedFilesManager.test.ts, packages/discovery/src/flatten/ParsedFilesManager.ts, packages/discovery/src/flatten/flatten.test.ts, packages/discovery/src/flatten/flattenStartingFrom.test.ts, packages/discovery/src/flatten/flattenStartingFrom.ts, packages/discovery/src/flatten/getASTIdentifiers.ts
=> Import more top level declarations

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/user/ArrayHandler.ts, packages/discovery/src/discovery/handlers/user/CallHandler.ts, packages/discovery/src/discovery/handlers/utils/callMethod.test.ts, packages/discovery/src/discovery/handlers/utils/callMethod.ts
=> Add the ability to pick out struct fields from call response

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/config/config.discovery.ts, packages/discovery/src/config/types.ts, packages/discovery/src/discovery/runDiscovery.ts
I've noticed there is no way to configure it, so I'm adding env variable for it.
I think it was there before (I see it in my local .env) but has been probably refactored out somehow.
=> Pull reorgSafeDepth (for discovery cache) from env

packages/discovery/CHANGELOG.md, packages/discovery/package.json, packages/discovery/src/discovery/handlers/utils/toContractValue.ts
=> Check for values smaller than MIN_SAFE_INTEGER
