l2beat/tools

.changeset/six-pans-arrive.md
packages/example/src/indexers/BlockIndexer.ts
packages/example/src/indexers/FakeClockIndexer.ts
packages/example/src/indexers/HourlyIndexer.ts
packages/uif/src/BaseIndexer.test.ts
packages/uif/src/BaseIndexer.ts
packages/uif/src/IndexerAction.ts
packages/uif/src/IndexerState.ts
packages/uif/src/indexerReducer.test.ts
packages/uif/src/indexerReducer.ts

Refine RootIndexer logic

---

packages/discovery-types/CHANGELOG.md
packages/discovery-types/package.json
packages/discovery-types/src/proxyDetails.ts
packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/provider/DiscoveryProvider.ts
packages/discovery/src/discovery/proxies/ProxyDetector.test.ts
packages/discovery/src/discovery/proxies/ProxyDetector.ts
packages/discovery/src/discovery/proxies/manual/OpticsBeaconProxy.ts

Using `ConstructorArgs` from the Etherscan API. Everything works nicely.
Resolves L2B-2484

Add manual OpticsBeaconProxy

---

.changeset/chilled-pots-change.md
packages/backend-tools/src/logger/Logger.test.ts
packages/backend-tools/src/logger/Logger.ts

Improve error reporting parameters

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/proxies/manual/OpticsBeaconProxy.ts

Run discovery on beaconController address in Optics Beacon Proxy

---

packages/discovery/src/discovery/config/ConfigReader.ts
packages/discovery/src/utils/fsLayer.ts

Enforce project case correctness

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ScrollAccessControlHandler.test.ts
packages/discovery/src/discovery/handlers/user/ScrollAccessControlHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts

Add ScrollAccessControlHandler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/config/ConfigReader.ts

Fix branch switching causing failing config verification

---

README.md

Update README.md to include info about versioning

---

packages/discovery/src/discovery/handlers/user/ScrollAccessControlHandler.ts

Reduced detectProxy call in Scroll access handler by provisioning required contracts (and their implementations') metadat before processing events.
Ref L2B-2836

Refactor ScrollAccessControl Handler

---

packages/discovery/CHANGELOG.md

Updated v0.19.1 changelog to include skept line

Insert scroll update in changelog

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/cli.ts
packages/discovery/src/cli/discoverCommand.ts
packages/discovery/src/cli/invertCommand.ts
packages/discovery/src/cli/singleDiscoveryCommand.ts
packages/discovery/src/index.ts
packages/discovery/src/singleDiscovery.ts

Export discover method 

---

packages/discovery-types/CHANGELOG.md
packages/discovery-types/package.json
packages/discovery-types/src/proxyDetails.ts
packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/proxies/auto/GnosisSafe.ts
packages/discovery/src/discovery/proxies/auto/ResolvedDelegateProxy.ts
packages/discovery/src/discovery/utils/getCallResult.ts

Added modules support to gnosis safe proxy
Added support for tuple response on calling contract methods
Ref L2B-2941

Gnosis Safe modules

---

packages/uif/CHANGELOG.md
packages/uif/package.json
packages/uif/src/BaseIndexer.ts

Add default starategy jsdoc

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/cli/getCliParameters.ts

Improve ChainId error in Discovery

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArrayHandler.test.ts
packages/discovery/src/discovery/handlers/user/ArrayHandler.ts

Needed for https://github.com/l2beat/l2beat/pull/2241/commits/a7627a459aa318b36db236320fc85baca3dd5c2e

Add indices field to the ArrayHandler

---

packages/discovery-types/CHANGELOG.md
packages/discovery-types/package.json
packages/discovery-types/src/proxyDetails.ts
packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/LineaRolesModuleHandler.test.ts
packages/discovery/src/discovery/handlers/user/LineaRolesModuleHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts
packages/discovery/src/discovery/proxies/ProxyDetector.ts
packages/discovery/src/discovery/proxies/auto/GnosisSafe.ts
packages/discovery/src/discovery/proxies/auto/GnosisSafeModule.ts

Part of L2B-3103
Resolves L2B-3128
Sample output for [this contract](https://gnosisscan.io/address/0x40034e442ecf9d3634034232eb64e66a508e838e#events)

Add Linea Role module handler as well as Zodiac Gnosis Safe Automatic detection

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArrayHandler.test.ts
packages/discovery/src/discovery/handlers/user/ArrayHandler.ts

Fixes a bug in Update Monitor returning array indices in indeterministic order

Fix array handler indeterministic indices

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/config/config.discovery.ts
packages/discovery/src/index.ts

Export discovery chain related configuration

---

packages/backend-tools/CHANGELOG.md
packages/backend-tools/package.json
packages/backend-tools/src/logger/Logger.test.ts
packages/backend-tools/src/logger/Logger.ts
packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/cli/discoverCommand.ts
packages/discovery/src/discovery/DiscoveryLogger.ts
packages/discovery/src/discovery/analysis/AddressAnalyzer.test.ts
packages/discovery/src/discovery/analysis/AddressAnalyzer.ts
packages/discovery/src/discovery/engine/DiscoveryEngine.test.ts
packages/discovery/src/discovery/engine/DiscoveryEngine.ts
packages/discovery/src/discovery/engine/DiscoveryStack.ts
packages/discovery/src/discovery/handlers/HandlerExecutor.ts
packages/discovery/src/discovery/handlers/user/LineaRolesModuleHandler.ts
packages/discovery/src/discovery/handlers/user/ScrollAccessControlHandler.ts
packages/discovery/src/discovery/proxies/ProxyDetector.test.ts
packages/discovery/src/discovery/proxies/ProxyDetector.ts

Resolves L2B-3121
The performance improvement from this is around ~2-2.5x

Map all stacked address to promises and then await using Promise.all

---

packages/discovery/src/discovery/handlers/user/LineaRolesModuleHandler.ts
packages/discovery/src/discovery/handlers/user/ScrollAccessControlHandler.ts
packages/discovery/src/discovery/utils/FunctionSelectorDecoder.test.ts
packages/discovery/src/discovery/utils/FunctionSelectorDecoder.ts
packages/discovery/src/discovery/utils/address.test.ts
packages/discovery/src/discovery/utils/address.ts

Extract function selector decoding to FunctionSelectorDecoder

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/utils/ChainId.ts

Add new ChainIds

---

packages/discovery-types/CHANGELOG.md
packages/discovery-types/package.json
packages/discovery-types/src/proxyDetails.ts
packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/proxies/ProxyDetector.test.ts
packages/discovery/src/discovery/proxies/ProxyDetector.ts
packages/discovery/src/discovery/proxies/auto/AxelarProxy.ts

Change AxelarProxy Handler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/provider/TransactionTrace.ts

Fix the trace_transaction zod parsing type

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/OpDAHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts
packages/discovery/src/discovery/handlers/utils/valueToAddress.ts
packages/discovery/src/discovery/provider/DiscoveryProvider.ts
packages/discovery/src/utils/EtherscanLikeClient.ts

Resolves L2B-3738
Example output:

Add OpStackDAHandler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArbitrumSequencerVersionHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts

Add an ArbitrumSequencerVersionHandler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArbitrumDACKeysetHandler.test.ts
packages/discovery/src/discovery/handlers/user/ArbitrumDACKeysetHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts
packages/discovery/src/utils/Bytes.ts

Add ArbitrumDACKeysetHandler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/OpSequencerInboxHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts
packages/discovery/src/utils/EtherscanLikeClient.ts

Add op stack sequencer inbox handler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/StateFromEventTupleHandler.test.ts
packages/discovery/src/discovery/handlers/user/StateFromEventTupleHandler.ts
packages/discovery/src/discovery/handlers/user/index.ts
packages/discovery/src/discovery/handlers/utils/toTopics.ts

Resolves L2B-3547
This PR is here so it's easy to pick up when we kick off the LZv2 CR.

Add state from event tuple handler

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/output/saveDiscoveryResult.ts
packages/discovery/src/flatten/getASTIdentifiers.ts

Fix errors flattening Scroll source code

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/flatten/ParsedFilesManager.ts
packages/discovery/src/flatten/flatten.test.ts

Resolves L2B-4128
Fixes Fraxtal

Support for context in import remappings

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/index.ts

Export Type for diffs in Update Monitor

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/output/diffToMarkdown.test.ts
packages/discovery/src/discovery/output/diffToMarkdown.ts
packages/discovery/src/discovery/utils/metaGetters.ts
packages/discovery/src/discovery/utils/normalizeDiffPath.test.ts
packages/discovery/src/discovery/utils/normalizeDiffPath.ts
packages/discovery/src/discovery/utils/sortDiffs.test.ts
packages/discovery/src/discovery/utils/sortDiffs.ts
packages/discovery/src/index.ts

Import discovery diff related things from L2BEAT

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/flatten/flattenStartingFrom.test.ts
packages/discovery/src/flatten/flattenStartingFrom.ts

Reencode flat result to always have unix line endings

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/OpDAHandler.ts
packages/discovery/src/utils/EtherscanLikeClient.ts

We'll check if the sequencer is sending blob txs. This is a heuristic but will be helpful.

Add OP stack blobs checker

---

schemas/meta.schema.json

Bring meta.schema.json up to speed

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArrayHandler.ts
packages/discovery/src/discovery/handlers/utils/callMethod.ts

Filtering the output of calls

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/config/DiscoveryMeta.ts
packages/discovery/src/discovery/output/toMetaOutput.test.ts
packages/discovery/src/discovery/output/toMetaOutput.ts
schemas/meta.schema.json

Add description to contracts in meta.json

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/config/DiscoveryMeta.ts
schemas/meta.schema.json

Rename STRUCTURE to CODE_CHANGE

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/flatten/ParsedFilesManager.ts

Fix PolygonZKEVM flattener errors

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/flatten/ParsedFilesManager.ts

Fix Mantle flattener errors

---

packages/uif-example/src/prices/PriceIndexer.ts
packages/uif/CHANGELOG.md
packages/uif/package.json
packages/uif/src/indexers/multi/MultiIndexer.test.ts
packages/uif/src/indexers/multi/MultiIndexer.ts

Add getSafeHeight and setSafeHeight to MultiIndexer

---

packages/discovery/CHANGELOG.md
packages/discovery/package.json
packages/discovery/src/discovery/handlers/user/ArbitrumSequencerVersionHandler.ts
packages/discovery/src/discovery/provider/DiscoveryProvider.test.ts
packages/discovery/src/discovery/provider/DiscoveryProvider.ts

Refactor getLogs to work backword and support event filtering
